version: '3.4'

services:
  mongodb:
    image: mongo
    container_name: demo-tasmocc-mongodb
    hostname: mongodb
    command: ["mongod", "--replSet", "rs0"]
    environment:
      - MONGO_INITDB_DATABASE=tasmocc
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
      - mongodb-db:/data/db
      - mongodb-configdb:/data/configdb

  mosquitto:
    image: eclipse-mosquitto
    container_name: demo-tasmocc-mosquitto
    hostname: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./docker/mosquitto.passwd:/mosquitto/config/mosquitto.passwd:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  tasmocc-emulator1:
    image: tasmocc-emulator:latest
    container_name: demo-tasmocc-emulator1
    ports:
      - "5001:80"

  tasmocc-emulator2:
    image: tasmocc-emulator:latest
    container_name: demo-tasmocc-emulator2
    ports:
      - "5002:80"

  tasmocc-emulator3:
    image: tasmocc-emulator:latest
    container_name: demo-tasmocc-emulator3
    ports:
      - "5003:80"

  tasmocc-service:
    image: tasmocc-service:latest
    container_name: demo-tasmocc-service
    environment:
      - MONGODB__CONNECTIONSTRING=mongodb://mongodb
      - MQTT__HOST=mosquitto
      - MQTT__USERNAME=devuser
      - MQTT__PASSWORD=devpassword
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

volumes:
  mongodb-db:
    name: demo-tasmocc-mongodb-db
  mongodb-configdb:
    name: demo-tasmocc-mongodb-configdb
  mosquitto-data:
    name: demo-tasmocc-mosquitto-data
  mosquitto-log:
    name: demo-tasmocc-mosquitto-log
